// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	productsv1 "github.com/Lineblaze/products_protos/gen/go/products"
	"golang.org/x/net/context"
)

// Controller describes methods, implemented by the grpc package.
type Handler interface {
	CreateProductCategory(ctx context.Context, req *productsv1.CreateProductCategoryRequest) (*productsv1.ProductCategoryResponse, error)
	GetProductCategory(ctx context.Context, req *productsv1.GetProductCategoryRequest) (*productsv1.ProductCategoryResponse, error)
	UpdateProductCategory(ctx context.Context, req *productsv1.UpdateProductCategoryRequest) (*productsv1.ProductCategoryResponse, error)
	DeleteProductCategory(ctx context.Context, req *productsv1.DeleteProductCategoryRequest) (*productsv1.DeleteProductCategoryResponse, error)
	GetProductCategories(ctx context.Context, req *productsv1.GetProductCategoriesRequest) (*productsv1.GetProductCategoriesResponse, error)
	CreateProduct(ctx context.Context, req *productsv1.CreateProductRequest) (*productsv1.ProductResponse, error)
	GetProduct(ctx context.Context, req *productsv1.GetProductRequest) (*productsv1.ProductResponse, error)
	UpdateProduct(ctx context.Context, req *productsv1.UpdateProductRequest) (*productsv1.ProductResponse, error)
	DeleteProduct(ctx context.Context, req *productsv1.DeleteProductRequest) (*productsv1.DeleteProductResponse, error)
	GetProducts(ctx context.Context, req *productsv1.GetProductsRequest) (*productsv1.GetProductsResponse, error)
}
