// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	"products/internal/models"

	productsv1 "github.com/Lineblaze/products_protos/gen/go/products"
	"golang.org/x/net/context"
)

// Controller describes methods, implemented by the Postgres package.
type Postgres interface {
	CreateProductCategory(ctx context.Context, input *models.CreateProductCategoryInput) (*productsv1.ProductCategory, error)
	GetProductCategory(ctx context.Context, id int64) (*productsv1.ProductCategory, error)
	UpdateProductCategory(ctx context.Context, input *models.UpdateProductCategoryInput) (*productsv1.ProductCategory, error)
	DeleteProductCategory(ctx context.Context, id int64) error
	GetProductCategories(ctx context.Context) ([]*productsv1.ProductCategory, error)
	CreateProduct(ctx context.Context, input *models.CreateProductInput) (*productsv1.Product, error)
	GetProduct(ctx context.Context, id int64) (*productsv1.Product, error)
	UpdateProduct(ctx context.Context, input *models.UpdateProductInput) (*productsv1.Product, error)
	DeleteProduct(ctx context.Context, id int64) error
	GetProducts(ctx context.Context) ([]*productsv1.Product, error)
}
