// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	models2 "products/internal/models"

	"golang.org/x/net/context"
)

// Controller describes methods, implemented by the usecase package.
type UseCase interface {
	CreateProductCategory(ctx context.Context, input *models2.CreateProductCategoryInput) (*models2.CreateProductCategoryOutput, error)
	GetProductCategory(ctx context.Context, id int64) (*models2.GetProductCategoryOutput, error)
	UpdateProductCategory(ctx context.Context, input *models2.UpdateProductCategoryInput) (*models2.UpdateProductCategoryOutput, error)
	DeleteProductCategory(ctx context.Context, id int64) error
	GetProductCategories(ctx context.Context) (*models2.GetProductCategoriesOutput, error)
	CreateProduct(ctx context.Context, input *models2.CreateProductInput) (*models2.CreateProductOutput, error)
	GetProduct(ctx context.Context, id int64) (*models2.GetProductOutput, error)
	UpdateProduct(ctx context.Context, input *models2.UpdateProductInput) (*models2.UpdateProductOutput, error)
	DeleteProduct(ctx context.Context, id int64) error
	GetProducts(ctx context.Context) (*models2.GetProductsOutput, error)
}
